#!/bin/sh

# This shell script is intended to be a quick way to build SaTScan and supporting
# libraries. Normally, I would have build a make file instead of this script but 
# the zd library make file produces an error when attempting to change user groups.
# The zd make error is harmless and I didn't want to start updating library files
# unless absolutely needed.
#
# I recommend running this script through some editor such as crisp so that the 
# output can be easily captured to an output window. Since this script just keeps
# on going should a make error occur, it may otherwise be difficult to determine
# which make invocation failed.

#make zlib
echo making zlib ...
cd zd/zd543/zlib
make clean 
make test CC=/opt/net/utils/gcc3.3.1/bin/gcc-3.3.1 -j8
echo zlib done
echo

#make zd
echo making zd ...						    
cd ..
make clean
make -r ZDVER=543 ZDSOURCEDIR=. ZDTARGETDIR=.. CC=/opt/net/utils/gcc3.3.1/bin/g++-3.3.1 -j8
echo zd done
echo

# make xbase
echo making xbase ...
cd ../../satscan/xbase/xbase_2.0.0/xbase
make clean
make CC=/opt/net/utils/gcc3.3.1/bin/g++-3.3.1 -j8
echo xbase done
echo

#make satscan
echo making SaTScan
cd ../../../unix_application
make clean SATSCAN=/home/hostovic/prj/satscan_dev/satscan BASIS=/home/hostovic/prj/satscan_dev/basisdev ZDVER=543 ZDDIR=/home/hostovic/prj/satscan_dev/zd ZDANNEX=/home/hostovic/prj/satscan_dev/zd SHELL=/bin/sh CC=/opt/net/utils/gcc3.3.1/bin/g++-3.3.1
make SATSCAN=/home/hostovic/prj/satscan_dev/satscan BASIS=/home/hostovic/prj/satscan_dev/basisdev ZDVER=543 ZDDIR=/home/hostovic/prj/satscan_dev/zd ZDANNEX=/home/hostovic/prj/satscan_dev/zd SHELL=/bin/sh CC=/opt/net/utils/gcc3.3.1/bin/g++-3.3.1 -j8
strip SaTScan
mv SaTScan ../..
echo SaTScan done
