; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SaTScan"
#define MyAppVersion "10.3"
#define MyAppPublisher "Information Management Services, Inc."
#define MyAppURL "https://www.satscan.org/"
#define MyAppExeName "SaTScan.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{AD0046EA-ADC2-4AD7-B623-ADC246EA46EA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=P:\satscan\licence\SaTScanLicenseAgreement.rtf
InfoBeforeFile=P:\satscan\build.area\satscan\installers\inno-setup\before-install.rtf
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=P:\satscan\installers\v.10.3.x
OutputBaseFilename=install-10_3_windows
;SetupIconFile=P:\satscan\build.area\satscan\installers\resources\SaTScan.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Only allow the installer to run on x64-compatible systems,
; and enable 64-bit install mode.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "P:\satscan\build.area\satscan\java_application\jni_application\dist\SaTScan.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "P:\satscan\build.area\satscan\java_application\jni_application\dist\lib\*"; DestDir: "{app}\lib"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "P:\satscan\build.area\satscan\installers\sample_data\*"; DestDir: "{app}\sample_data"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "P:\satscan\build.area\satscan\installers\java\jre_x64\*"; DestDir: "{app}\jre"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "P:\satscan\build.area\satscan\installers\documents\eula.html"; DestDir: "{app}"; Flags: ignoreversion
Source: "P:\satscan\build.area\satscan\installers\documents\SaTScan_Users_Guide.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "P:\satscan\build.area\satscan\batch_application\x64\Release\SaTScanBatch64.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "P:\satscan\build.area\satscan\shared_library\x64\Release\satscan64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "P:\satscan\build.area\satscan\java_application\jni_application\dist\SaTScan.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "P:\satscan\build.area\satscan\installers\inno-setup\curl.exe"; DestDir: "{app}"; OnlyBelowVersion: 10.0
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

