/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_satscan_app_Parameters */

#ifndef _Included_org_satscan_app_Parameters
#define _Included_org_satscan_app_Parameters
#ifdef __cplusplus
extern "C" {
#endif
#undef org_satscan_app_Parameters_MAXIMUM_ITERATIVE_ANALYSES
#define org_satscan_app_Parameters_MAXIMUM_ITERATIVE_ANALYSES 32000L
#undef org_satscan_app_Parameters_MAXIMUM_ELLIPSOIDS
#define org_satscan_app_Parameters_MAXIMUM_ELLIPSOIDS 10L
/*
 * Class:     org_satscan_app_Parameters
 * Method:    Read
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_satscan_app_Parameters_Read
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_satscan_app_Parameters
 * Method:    Write
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_satscan_app_Parameters_Write
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
