/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_satscan_importer_ShapefileDataSource */

#ifndef _Included_org_satscan_importer_ShapefileDataSource
#define _Included_org_satscan_importer_ShapefileDataSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_satscan_importer_ShapefileDataSource
 * Method:    getNumberOfShapes
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_satscan_importer_ShapefileDataSource_getNumberOfShapes
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_satscan_importer_ShapefileDataSource
 * Method:    isSupportedProjection
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_satscan_importer_ShapefileDataSource_isSupportedProjection
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_satscan_importer_ShapefileDataSource
 * Method:    isSupportedShapeType
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_satscan_importer_ShapefileDataSource_isSupportedShapeType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_satscan_importer_ShapefileDataSource
 * Method:    getCoordinates
 * Signature: (Ljava/lang/String;JZLjava/lang/String;IDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_satscan_importer_ShapefileDataSource_getCoordinates
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
