/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_satscan_utils_FileAccess */

#ifndef _Included_org_satscan_utils_FileAccess
#define _Included_org_satscan_utils_FileAccess
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_satscan_app_AppConstants
 * Method:    getVersionId
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_satscan_utils_FileAccess_getFormatSubstitutedFilename(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
