/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_satscan_gui_OberservableRegionsFrame */

#ifndef _Included_org_satscan_gui_OberservableRegionsFrame
#define _Included_org_satscan_gui_OberservableRegionsFrame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_satscan_gui_OberservableRegionsFrame
 * Method:    _getRegionIsValid
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_satscan_gui_OberservableRegionsFrame__1getRegionIsValid
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_satscan_gui_OberservableRegionsFrame
 * Method:    _getRegionIsValidRegionCollection
 * Signature: (Ljava/util/Vector;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_satscan_gui_OberservableRegionsFrame__1getRegionIsValidRegionCollection
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
