/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.satscan.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.undo.UndoManager;
import org.satscan.app.BatchAnalysis;
import org.satscan.gui.utils.Utils;

/**
 *
 * @author hostovic
 */
public class StudyPeriodOffsetDialog extends javax.swing.JDialog implements ActionListener {
    private BatchAnalysis.StudyPeriodOffset _study_period_offset;
    private boolean _updated = false;
    private final UndoManager undo = new UndoManager();
    private int _minimum_value = 0;
    
    /**
     * Creates new form StudyPeriodOffsetDialog
     */
    public StudyPeriodOffsetDialog(java.awt.Frame parent) {
        super(parent, "Edit Study Period Offset", true);
        initComponents();
        _ok.addActionListener( this );
        _cancel.addActionListener( this );
        enableControls();
    }

    public void setStudyPeriodOffset(String title, String toggleText, String helpInfo, BatchAnalysis.StudyPeriodOffset obj, int minumum_value) {
        _minimum_value = minumum_value;
        setTitle(title);
        _toggle_no_offset.setText(toggleText);
        _text_area_help.setText(helpInfo);
        _text_area_help.setCaretPosition(0);
        _study_period_offset = obj;
        if (_study_period_offset == null) {
            _toggle_no_offset.setSelected(true);
            _offset_value.setText("365");
            _offset_units.setSelectedItem("day");
        } else {
            _toggle_no_offset.setSelected(false);
            _offset_value.setText(Integer.toString(Math.max(obj.getOffset(), _minimum_value)));
            switch (obj.getUnits()) {
                case YEAR : _offset_units.setSelectedItem("year"); break;
                case MONTH : _offset_units.setSelectedItem("month"); break;
                case DAY : _offset_units.setSelectedItem("day"); break;
                case GENERIC : _offset_units.setSelectedItem("generic"); break;
            }
        }
        enableControls();
    }
    
    public BatchAnalysis.StudyPeriodOffset getStudyPeriodOffset() {
        return _study_period_offset;
    }
    
    private void enableControls() {
        _offset_value.setEnabled(!_toggle_no_offset.isSelected());
        _offset_units.setEnabled(!_toggle_no_offset.isSelected());
    }
    
    public boolean updatedOffset() {
        return _updated;
    }
    
    /* Save the changed text before hiding the popup. */
    public void actionPerformed(ActionEvent e) {
        if ("Ok".equals( e.getActionCommand() ) ) {
            if (!_toggle_no_offset.isSelected()) {
                _study_period_offset = new BatchAnalysis.StudyPeriodOffset();
                _study_period_offset.setOffset(Integer.parseInt(_offset_value.getText()));
                switch (_offset_units.getSelectedIndex()) {
                    case 0 : _study_period_offset.setUnits(BatchAnalysis.UNITS.YEAR); break;
                    case 1 : _study_period_offset.setUnits(BatchAnalysis.UNITS.MONTH); break;
                    case 2 : _study_period_offset.setUnits(BatchAnalysis.UNITS.DAY); break;
                    case 3 : _study_period_offset.setUnits(BatchAnalysis.UNITS.GENERIC); break;
                }
            } else
                _study_period_offset = null;
            _updated = true;
        }
        setVisible(false);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        _offset_value = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        _offset_units = new javax.swing.JComboBox<>();
        _cancel = new javax.swing.JButton();
        _ok = new javax.swing.JButton();
        _toggle_no_offset = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        _text_area_help = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Duration");

        _offset_value.setText("365");
        _offset_value.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent e) {
                while (_offset_value.getText().length() == 0) {
                    if (undo.canUndo())
                    undo.undo();
                    else
                    _offset_value.setText(Integer.toString(_minimum_value));
                }
                if (Integer.parseInt(_offset_value.getText()) < _minimum_value)
                _offset_value.setText(Integer.toString(_minimum_value));
            }
        });
        _offset_value.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                Utils.validatePostiveNumericKeyTyped(_offset_value, e, 6);
            }
        });
        _offset_value.getDocument().addUndoableEditListener(new UndoableEditListener() {
            public void undoableEditHappened(UndoableEditEvent evt) {
                undo.addEdit(evt.getEdit());
            }
        });
        _offset_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _offset_valueActionPerformed(evt);
            }
        });

        jLabel2.setText("Units");

        _offset_units.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "month", "day", "generic" }));

        _cancel.setText("Cancel");

        _ok.setText("Ok");

        _toggle_no_offset.setText("No Offset");
        _toggle_no_offset.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent e) {
                enableControls();
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("What is this?"));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        _text_area_help.setEditable(false);
        _text_area_help.setColumns(20);
        _text_area_help.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _text_area_help.setLineWrap(true);
        _text_area_help.setRows(5);
        _text_area_help.setText("Lag is an offset from today, as in the day which the analysis is performed each time. This offset date is used in place of the study period end date.");
        _text_area_help.setWrapStyleWord(true);
        jScrollPane1.setViewportView(_text_area_help);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(_toggle_no_offset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(_offset_value, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(_offset_units, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_offset_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_offset_units, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_toggle_no_offset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_ok)
                            .addComponent(_cancel))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _offset_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__offset_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__offset_valueActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _cancel;
    private javax.swing.JComboBox<String> _offset_units;
    private javax.swing.JTextField _offset_value;
    private javax.swing.JButton _ok;
    private javax.swing.JTextArea _text_area_help;
    private javax.swing.JCheckBox _toggle_no_offset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
