#!/bin/sh

binaries="/prj/satscan/build.area/binaries/solaris"
satscan_src="/prj/satscan/build.area/satscan"
boost_src="/prj/satscan/build.area/boost/boost_1_46_0"
processors="-j1"
pthread="-pthreads"

rm -f $binaries/*

echo building SaTScan for 32-bit system using gcc3.3.1
../makescript.sh $binaries/satscan_gcc3.3.1_sparc_32bit $satscan_src $boost_src -m32 -O3 /opt/net/utils/bin/g++-3.3.1 $processors $pthread

echo building SaTScan shared object for 32-bit system using gcc3.3.1
../makescript.so.sh libsatscan.solaris.so $binaries/libsatscan.gcc3.3.1_sparc_32bit.so $satscan_src $boost_src -m32 -O3 /opt/net/utils/bin/g++-3.3.1 $processors $pthread

##   fails with: /usr/ccs/bin/as: "/var/tmp//ccNPkKc9.s", line 1903: error: invalid (misaligned) register
##   echo building SaTScan for 64-bit system using gcc3.3.1
##   ../makescript.sh $binaries/satscan_gcc3.3.1_sparc_64bit $satscan_src $boost_src -m64 -O3 /opt/net/utils/bin/g++-3.3.1 $processors  $pthread

echo building SaTScan for 32-bit system using gcc3.4.4
../makescript.sh $binaries/satscan_gcc3.4.4_sparc_32bit $satscan_src $boost_src -m32 -O3 /opt/net/utils/bin/g++-3.4.4 $processors $pthread

echo building SaTScan shared object for 32-bit system using gcc3.4.4
../makescript.so.sh libsatscan.solaris.so $binaries/libsatscan.gcc3.4.4_sparc_32bit.so $satscan_src $boost_src -m32 -O3 /opt/net/utils/bin/g++-3.4.4 $processors $pthread

echo building SaTScan v8.0 for 64-bit system using gcc3.4.4
../makescript.sh $binaries/satscan_gcc3.4.4_sparc_64bit $satscan_src $boost_src -m64 -O3 /opt/net/utils/bin/g++-3.4.4 $processors $pthread

echo building SaTScan shared object for 64-bit system using gcc3.4.4
../makescript.so.sh libsatscan.solaris.so $binaries/libsatscan.gcc3.4.4_sparc_64bit.so $satscan_src $boost_src -m64 -O3 /opt/net/utils/bin/g++-3.4.4 $processors $pthread
